name: alertmanager
description: Handle alerts and notifications for the Prometheus ecosystem
category: Infrastructure
updated: true
version: v0.31.1
upstream:
  type: github
  repo: prometheus/alertmanager
  strategy: latest_release
build:
  method: binary_repack
  binary_name: alertmanager
  extra_binaries:
  - amtool
  extra_sources: []
  archs:
  - amd64
  - arm64
artifacts:
  rpm:
    enabled: true
    targets:
    - el8
    - el9
    - el10
    summary: Prometheus Alertmanager
    dependencies: []
    systemd:
      enabled: true
      arguments: []
      after:
      - network.target
      restart: on-failure
      type: simple
    system_user: alertmanager
    extra_files:
    - source: assets/alertmanager.yml
      dest: /etc/alertmanager/alertmanager.yml
      mode: '0644'
      config: true
    directories:
    - path: /etc/alertmanager
      mode: '0755'
      owner: root
      group: root
    - path: /var/lib/alertmanager
      mode: '0755'
      owner: alertmanager
      group: alertmanager
  deb:
    enabled: true
    targets:
    - ubuntu-22.04
    - ubuntu-24.04
    - debian-12
    - debian-13
    summary: Handle alerts and notifications for the Prometheus ecosystem
    systemd:
      enabled: true
      arguments: []
      after:
      - network.target
      restart: on-failure
      type: simple
    system_user: alertmanager
    dependencies: []
    extra_files:
    - source: assets/alertmanager.yml
      dest: /etc/alertmanager/alertmanager.yml
      mode: '0644'
      config: true
    directories:
    - path: /etc/alertmanager
      mode: '0755'
      owner: root
      group: root
    - path: /var/lib/alertmanager
      mode: '0755'
      owner: alertmanager
      group: alertmanager
    section: net
    priority: optional
  docker:
    enabled: true
    base_image: registry.access.redhat.com/ubi9/ubi-minimal
    entrypoint:
    - /usr/bin/alertmanager
    cmd:
    - --config.file=/etc/alertmanager/alertmanager.yml
    validation:
      enabled: true
      port: 9093
